default:
  image: gradle:jdk14

variables:
  JACOCO_OUTPUT_LOCATION: '$CI_PROJECT_DIR/build/jacocoCsv'

stages:
  - build
  - test
  - visualize

test-domain:
  stage: test
  image: gradle:6.6.1-jdk11
  script:
    - 'gradle :domain:test'
    - 'gradle test jacocoTestReport'
  artifacts:
    paths: 
      - domain/build/jacoco/jacoco.xml
    reports:
      junit: domain/build/test-results/test/**/TEST-*.xml

build-domain:
  stage: build
  script:
    - gradle :domain:assemble
  artifacts:
      paths:
        - domain/build/libs/domain

coverage-domain:
  stage: visualize
  image: registry.gitlab.com/haynes/jacoco2cobertura:1.0.7 
  # taken from example on https://docs.gitlab.com/ee/user/project/merge_requests/test_coverage_visualization.html 
  script:
    # convert report from jacoco to cobertura, using relative project path
    - python /opt/cover2cover.py domain/build/jacoco/jacoco.xml $CI_PROJECT_DIR/src/main/java/ > domain/build/cobertura.xml
  needs: ["test-domain"]
  dependencies:
    - test-domain
  artifacts:
    reports:
      cobertura: domain/build/cobertura.xml
