default:
  image: gradle:jdk14

stages:
  - test
  - build

test-domain:
  stage: test
  script:
    - gradle :domain:test
  artifacts:
    reports:
      junit: domain/build/test-results/test

build-domain:
  stage: build
  script:
    - gradle :domain:build
  artifacts:
        paths:
        - domain/build/libs/domain


