default:
  image: gradle:jdk14

stages:
  - build
  - test

build-domain:
  stage: build
  script:
    - gradle :domain:build
  artifacts:
        paths:
        - domain/build/libs/domain.jar

test-domain:
  stage: test
  script:
    - gradle :domain:test
  needs: ["buildDomain"]
  dependencies:
    - buildDomain
  artifacts:
    reports:
      junit: domain/build/test-results/test/**/TEST-*.xml
