default:
  image: gradle:jdk14

variables:
  JACOCO_CSV_LOCATION: '$buildDir/reports/jacoco/test'

stages:
  - build
  - test

test-domain:
  stage: test
  script:
    - gradle :domain:test
    - awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/", instructions, " instructions covered"; print 100*covered/instructions, "% covered" }' $JACOCO_CSV_LOCATION
  artifacts:
    reports:
      junit: domain/build/test-results/test/**/TEST-*

build-domain:
  stage: build
  script:
    - gradle :domain:assemble
  artifacts:
        paths:
        - domain/build/libs/domain


